### PR TITLE
chore: change targetsdk and compilesdk to 29

### LINKED ISSUE #77: Change App target API to 29
**Is your feature request related to a problem? Please describe.**
With the release of Android 11, Google recommends any app that is uploaded to the Play Store should target API level 29. From November 2020, Google is mandating all the apps to target API 29. 

Message from PlayStore:

> Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.
From August 2020, new apps must target at least Android 10 (API level 29).
From November 2020, app updates must target Android 10 (API level 29).

**Describe the solution you'd like**
Upgrade the API level in the app level `build.gradle` to 29

**Describe alternatives you've considered**
N/A

### PR DESCRIPTION
**Pull request by BumbleFlash**
This PR is to change the API level to 29. 

"closes #77"

### CODE REVIEW

**Comment by BumbleFlash** [comment]
@barbeau I read through the checklist and I think MUSER doesn't have anything in the codebase that could be potentially be affected. I also did a `Ctrl + Shift + F` on the Studio and I think it looks good to me. Also, I tested it out on my Pixel 3a (Android 11) and I didn't notice any crashes. IIRC, AVD manager currently doesn't have an Android 11 but I think you can also test it out on Android 10 with AP1 29? Lastly, changing the API level doesn't change the notification bar behaviour on my phone (#85)

**Comment by barbeau** [comment]
@BumbleFlash Thanks! There should be an Android 11 emulator now if you update to the latest stable tools, I have one set up on my machine. Did you test to see if Firebase and Google Sheets logging works as expected on the Pixel 3a?

**Comment by BumbleFlash** [comment]
@barbeau I double-checked Firebase logging an email mapping and it seems to work fine on my Pixel 3a.

**Review by barbeau — APPROVED** [review]
👍

**Comment by barbeau** [comment]
@BumbleFlash Could you go ahead and do another PR to bump `versionCode` and `versionName`, and we'll get another release out with this included so more users can test?

**Comment by barbeau** [comment]
You can just do a patch version - `v1.1.2`

**Comment by BumbleFlash** [comment]
@barbeau Sounds good. Will surely do.

**Pull request merged**
