### PR TITLE
feat: force theme v2

### LINKED ISSUE #60: Fix compatibility issue with Android 9, API LEVEL < 29
**Describe the bug**
The text on the mini player is not readable when the dark mode is switched on. 

**To Reproduce**
1. Open Muser
2. Go to settings->Base Theme --> Select Dark
3. Play a song

**Expected behavior**
The text on the mini player should be visible and not camouflage with the dark theme. 

**Observed behavior**
The text on the mini player is almost invisible and camouflages with the dark theme. 

**Device and Android version:** 

Google Pixel. Android 9, API LEVEL 28.

**Screenshots:**

### PR DESCRIPTION
**Pull request by BumbleFlash**
This PR is to force the default MUSER colors to the app by setting the "Only on Now-Playing Screen" at all times. This PR also allows the user to customize themes and set the default theme on one click. 

Changes include:-

- [x] Revert the last force theme PR.
- [x] Set the now playing preference to be true by default and make the preference invisible. 
- [x] Set the default theme of the App to be `AppTheme.Light`
- [x] Add a preference click that sets the default theme in one click. Found Settings -> Themes -> Set Default Theme

"Closes #60"

### CODE REVIEW

**Comment by barbeau** [comment]
@BumbleFlash Thanks for putting this together! I just ran a fresh install of this, but I don't see the MUSER blue theme colors on the action bar:

image

**Comment by BumbleFlash** [comment]
@barbeau That's weird. I just tested this branch after a fresh install and it seems to be working as expected. Could you please check if AS has pulled all the commits? Rarely, the IDE might fail to pull all the commits. Happened to me once a couple of years back.

**Comment by barbeau** [comment]
I'll give it a try. I'm still testing Android 9.

**Comment by barbeau** [comment]
I pulled the branch again from GitHub, check Git log to make sure it's updated with this PR, invalidated cache in AS and did a fresh install on Samsung Galaxy S8+ w/ Android 9 and I'm still not seeing the blue theme colors on startup:

image

Strangely, I'm not seeing this on an emulator based on Pixel 2 w/ API 28 (Android 9) when installing same code:

image

I don't have any music loaded on the emulator -maybe that matters, if it causes a callback to be delayed when scanning the device?

**Comment by barbeau** [comment]
So if I watch the first launch of the app carefully on the Samsung S8+, I can see the blue theme color get set correctly initially, but then it fades to a darker blue when the permission screen is visible, and then completely to black after granting storage permission. I recorded via screencapture as a video, which is in the zip below:

[samsung-galaxy-s8-plus-no-blue-theme.zip](https://github.com/CUTR-at-USF/MUSER/files/5256697/samsung-galaxy-s8-plus-no-blue-theme.zip)

(EDIT: Note that you'll have to skip to the middle of the video to see it launch - it took a while to load and for some reason I couldn't trim the video on my machine)

**Comment by barbeau** [comment]
If I kill the app and then restart it, I see a similar startup where the status bar initially has the blue background (and the main screen is white while it loads) and then the status bar turns to black when the UI loads, which is also all black.

**Comment by BumbleFlash** [comment]
@barbeau thank you for taking the time to record the video and testing it on the emulator too, I used Pixel with Android 9 (loaded with music) and it seems to be working fine as expected. Sadly, I'm not able to reproduce the bug from the video. 

I'm guessing Android in Samsung is cacheing data for faster install? Altenatively, could you try deleting any data and cache associated with the app from the Settings and try reinstalling again? I'm not sure if this is causing the issue but I think we should double check it. 
If that doesn't work, I can try setting the themes again on start up using `Aesthetic` and hopefully that should solve the issue in any device.

**Comment by barbeau** [comment]
>I'm guessing Android in Samsung is cacheing data for faster install? 

My guess would be the opposite - it's taking longer to execute on a Samsung device than an emulator.

>Altenatively, could you try deleting any data and cache associated with the app from the Settings and try reinstalling again? 

Data and cache are deleted when you uninstall the app (the app is removed from the Settings at this point, so you there isn't an option to delete after an uninstall)

**Comment by BumbleFlash** [comment]
@barbeau I just set the theme using Aesthetic and hopefully, this should solve the problem. Let me know if this doesn't work.  

Also I tested this branch on Nexus 5 w/ Android 9, there is no problems on that device either.

**Review by barbeau — APPROVED** [review]
@BumbleFlash Looks great, that did it!

image

**Pull request merged**
