### PR TITLE
feat: collect new UI events

### PR DESCRIPTION
**Pull request by BumbleFlash**
This PR is to capture the next set of UI_EVENTS as listed in #17. 

Changes:-

- [x] PLAY_NEXT, PLAY_ALBUM_ARTIST_NEXT, PLAY_ALBUM_NEXT and PLAY_GENRE_NEXT.
- [x] ADD_TO_PLAYLIST, ADD_TO_PLAYLIST_ALBUM_ARTIST, ADD_TO_PLAYLIST_ALBUM and ADD_TO_PLAYLIST_GENRE
- [x] DELETE, DELETE_ALBUM_ARTIST, and DELETE_ALBUM
- [x] ALBUM_SHUFFLE
~~- [ ] BLACKLISTS~~

### CODE REVIEW

**Comment by barbeau** [comment]
@BumbleFlash Before adding any tracking for the current BLACKLISTS features let's address https://github.com/CUTR-at-USF/MUSER/issues/114 and https://github.com/CUTR-at-USF/MUSER/issues/115 (including renaming to "Disable").

**Comment by barbeau** [comment]
@BumbleFlash Is this ready for review or still waiting on the shuffle implementation?

**Comment by BumbleFlash** [comment]
@barbeau I just pushed a commit to capture the `ALBUM_SHUFFLE` event. And yes, it's ready for review!

**Review by barbeau — APPROVED** [review]
Looks great, thanks @BumbleFlash! 👍

**Pull request merged**
