### PR TITLE
feat: add ALBUM_SHUFFLE events

### PR DESCRIPTION
**Pull request by BumbleFlash**
This PR captures ALBUM_SHUFFLE, ARTIST_ALBUM_SHUFFLE and ALBUM_SONGS_SHUFFLE events

Part of #17

### CODE REVIEW

**Comment by BumbleFlash** [comment]
@barbeau I'm puzzled about what model class should I choose to collect when I click on the Album Shuffle in the screenshot here.



Since it belongs to the parent fragment and not to a particular album or artist or song, I'm not sure what class I should choose.

**Comment by barbeau** [comment]
>I'm puzzled about what model class should I choose to collect when I click on the Album Shuffle in the screenshot here.

@BumbleFlash This just shuffles all albums in the library, right? If so then I don't think you need a model class along with the event - otherwise you'd need to somehow include all albums in the library. So I think just the Album Shuffle event data is fine.

**Comment by barbeau** [comment]
@BumbleFlash Looks like there is a conflict on this PR. Could you resolve?

**Review by barbeau — APPROVED** [review]
LGTM!

**Pull request merged**
